import { useMemo } from 'react';
import { useStore } from '../store';
import type { Lang } from './types';

export const LANGUAGES: Array<{ id: Lang; label: string }> = [
  { id: 'en', label: 'English' },
  { id: 'hi', label: 'हिन्दी (Hindi)' },
];

/* Only the customer-facing screens are translated. The Staff area stays in
   English: it is used by the same few people every day, and keeping one
   language there means a support conversation is never about which words the
   shop is looking at. */

const en: Record<string, string> = {
  'nav.home': 'Home',
  'nav.collection': 'Collection',
  'nav.selection': 'My selection',
  'nav.selectionCount': 'My selection ({n})',
  'common.staff': 'Staff',
  'common.back': '← Back',
  'common.backToCollection': '← Collection',
  'common.cancel': 'Cancel',
  'common.remove': 'Remove',
  'common.size': 'Size',
  'common.pieceOne': '1 piece',
  'common.pieceMany': '{n} pieces',

  'cat.All': 'All',
  'cat.Sarees': 'Sarees',
  'cat.Kurtis': 'Kurtis',
  'cat.Dresses': 'Dresses',
  'cat.Lehengas': 'Lehengas',
  'cat.Blouses': 'Blouses',

  'home.title': 'See yourself in our collection',
  'home.photoReady': 'Your photo is ready',
  'home.photoReadyHint': 'Pick anything below to try it on',
  'home.retake': 'Retake',
  'home.intro': 'Take one full-body photo and try on anything in the shop without leaving your seat.',
  'home.takePhoto': 'Take your photo',
  'home.newThisWeek': 'New this week',
  'home.seeAll': 'See all',
  'home.emptyCatalogue': 'The catalogue is empty. A staff member can add pieces from the Staff area.',

  'collection.title': 'Collection',
  'collection.search': 'Search sarees, kurtis, colours…',
  'collection.searchLabel': 'Search the collection',
  'collection.empty': 'Nothing here yet. Try another category, or ask a staff member what’s just come in.',

  'photo.title': 'Take your photo',
  'photo.tip1': 'Stand about two steps back, facing the camera',
  'photo.tip2': 'Keep your whole body in frame, head to shoes',
  'photo.tip3': 'A plain wall and good light give the best result',
  'photo.privacy': 'Your photo stays on this tablet and is never posted anywhere. Delete it yourself at any time from the pickup screen, and it goes automatically when the tablet is cleared for the next person.',
  'photo.privacyGemini': ' The try-on itself is generated by Google Gemini, so the photo is sent there to be processed.',
  'photo.previewTitle': 'Looking good?',
  'photo.yourPhoto': 'Your photo',
  'photo.badgeBody': 'Full body visible',
  'photo.badgeLight': 'Good light',
  'photo.usePhoto': 'Use this photo',

  'cam.guide': 'Stand so your whole body fits the outline',
  'cam.take': 'Take the photo',
  'cam.saving': 'Saving…',
  'cam.switch': 'Switch camera',
  'cam.open': 'Open camera',
  'cam.opening': 'Opening camera…',
  'cam.upload': 'Upload from device',
  'cam.denied': 'Camera permission was refused. Allow it in the browser settings, or upload a photo instead.',
  'cam.unsupported': 'No camera available on this device. Upload a photo instead.',
  'cam.badFile': 'That file could not be read as an image.',

  'product.gone': 'That piece is no longer in the catalogue.',
  'product.stock': '{n} in stock',
  'product.tryOn': 'Try it on',
  'product.needPhoto': 'Take a photo to try it on',
  'product.addToSelection': 'Add to my selection',

  'step.reading': 'Reading your photo',
  'step.shape': 'Matching your shape',
  'step.fitting': 'Fitting the garment',
  'step.drape': 'Smoothing the drape',
  'step.ready': 'Ready',
  'processing.waitGemini': 'Usually about 20 seconds. Keep this screen open.',
  'processing.waitDemo': 'Just a moment. Keep this screen open.',
  'processing.label': 'Creating your try-on',

  'result.before': 'Your photo',
  'result.after': 'With this on',
  'result.demoNotice': 'This is a demo preview, not a real fit — the garment photo is laid over yours so staff can test the flow.',
  'result.save': 'Save to my selection',
  'result.share': 'Send to family on WhatsApp',
  'result.sharePrivacy': 'Sharing sends this picture off the tablet to whoever you choose. Nothing is sent unless you tap.',
  'result.shareGone': 'That try-on is no longer available.',
  'result.shareTextOnly': 'Only the message could be sent from this device. Take a screenshot to send the picture.',
  'result.shareNone': 'Sharing is not available on this device. Take a screenshot to send the picture.',
  'result.shareFailed': 'Could not open sharing on this device. Take a screenshot instead.',
  'result.browse': 'Browse everything',
  'result.next': 'Try the next one on',

  'selection.title': 'My selection',
  'selection.empty': 'Nothing saved yet. Try a few pieces on and keep the ones you like here.',
  'selection.browse': 'Browse the collection',
  'selection.inStock': 'In stock',
  'selection.lowStock': 'Only {n} left',
  'selection.outOfStock': 'Out of stock',
  'selection.checkout': 'Show shop staff',
  'selection.checkoutHint': 'Staff will bring only these pieces to the trial room.',

  'code.title': 'Show this to any staff member',
  'code.label': 'Pickup code',
  'code.photoHere': 'Your photo is still on this tablet so you can try more pieces on. Delete it whenever you like.',
  'code.deletePhoto': 'Delete my photo',
  'code.tryMore': 'Try more pieces',
  'code.photoDeleted': 'Your photo and try-ons have been deleted from this tablet. Your code above still works.',
  'code.newSelection': 'Start a new selection — keep my photo',
  'code.finish': 'Finish — next customer',
  'code.finishHint': 'Finishing deletes the photo and clears the tablet for the next person.',

  'error.photoGone': 'Your photo is no longer available. Please take it again.',
  'error.tryOn': 'Something went wrong with the try-on.',
};

const hi: Record<string, string> = {
  'nav.home': 'होम',
  'nav.collection': 'कलेक्शन',
  'nav.selection': 'मेरी पसंद',
  'nav.selectionCount': 'मेरी पसंद ({n})',
  'common.staff': 'स्टाफ',
  'common.back': '← पीछे',
  'common.backToCollection': '← कलेक्शन',
  'common.cancel': 'रहने दीजिए',
  'common.remove': 'हटाइए',
  'common.size': 'साइज़',
  'common.pieceOne': '1 पीस',
  'common.pieceMany': '{n} पीस',

  'cat.All': 'सभी',
  'cat.Sarees': 'साड़ी',
  'cat.Kurtis': 'कुर्ती',
  'cat.Dresses': 'ड्रेस',
  'cat.Lehengas': 'लहंगा',
  'cat.Blouses': 'ब्लाउज़',

  'home.title': 'हमारे कलेक्शन में खुद को देखिए',
  'home.photoReady': 'आपकी फोटो तैयार है',
  'home.photoReadyHint': 'नीचे से कुछ भी चुनकर ट्राई कीजिए',
  'home.retake': 'दोबारा लीजिए',
  'home.intro': 'एक बार पूरी फोटो लीजिए और अपनी जगह पर बैठे-बैठे दुकान की कोई भी चीज़ ट्राई कीजिए।',
  'home.takePhoto': 'अपनी फोटो लीजिए',
  'home.newThisWeek': 'इस हफ्ते का नया',
  'home.seeAll': 'सब देखिए',
  'home.emptyCatalogue': 'कैटलॉग खाली है। स्टाफ एरिया से पीस जोड़े जा सकते हैं।',

  'collection.title': 'कलेक्शन',
  'collection.search': 'साड़ी, कुर्ती, रंग खोजिए…',
  'collection.searchLabel': 'कलेक्शन में खोजिए',
  'collection.empty': 'यहाँ अभी कुछ नहीं है। दूसरी कैटेगरी देखिए, या स्टाफ से पूछिए कि नया क्या आया है।',

  'photo.title': 'अपनी फोटो लीजिए',
  'photo.tip1': 'कैमरे की तरफ मुँह करके दो कदम पीछे खड़ी हों',
  'photo.tip2': 'सिर से पाँव तक पूरा शरीर फ्रेम में रखिए',
  'photo.tip3': 'सादी दीवार और अच्छी रोशनी से सबसे अच्छा नतीजा आता है',
  'photo.privacy': 'आपकी फोटो इसी टैबलेट में रहती है और कहीं नहीं भेजी जाती। आप इसे कोड वाली स्क्रीन से कभी भी मिटा सकती हैं, और अगले ग्राहक के लिए टैबलेट साफ़ करते ही यह अपने आप हट जाती है।',
  'photo.privacyGemini': ' ट्राई-ऑन गूगल जेमिनी बनाता है, इसलिए फोटो प्रोसेस होने के लिए वहाँ भेजी जाती है।',
  'photo.previewTitle': 'अच्छी लग रही है?',
  'photo.yourPhoto': 'आपकी फोटो',
  'photo.badgeBody': 'पूरा शरीर दिख रहा है',
  'photo.badgeLight': 'अच्छी रोशनी',
  'photo.usePhoto': 'यही फोटो लीजिए',

  'cam.guide': 'इस निशान में आपका पूरा शरीर आ जाए, ऐसे खड़ी हों',
  'cam.take': 'फोटो लीजिए',
  'cam.saving': 'सेव हो रही है…',
  'cam.switch': 'कैमरा बदलिए',
  'cam.open': 'कैमरा खोलिए',
  'cam.opening': 'कैमरा खुल रहा है…',
  'cam.upload': 'फोन से फोटो चुनिए',
  'cam.denied': 'कैमरे की अनुमति नहीं मिली। ब्राउज़र सेटिंग में अनुमति दीजिए, या फोटो अपलोड कीजिए।',
  'cam.unsupported': 'इस डिवाइस में कैमरा नहीं है। फोटो अपलोड कीजिए।',
  'cam.badFile': 'यह फाइल फोटो के रूप में नहीं खुल पाई।',

  'product.gone': 'यह पीस अब कैटलॉग में नहीं है।',
  'product.stock': 'स्टॉक में {n}',
  'product.tryOn': 'ट्राई कीजिए',
  'product.needPhoto': 'ट्राई करने के लिए फोटो लीजिए',
  'product.addToSelection': 'मेरी पसंद में जोड़िए',

  'step.reading': 'आपकी फोटो पढ़ी जा रही है',
  'step.shape': 'आपका नाप मिलाया जा रहा है',
  'step.fitting': 'कपड़ा पहनाया जा रहा है',
  'step.drape': 'ड्रेप ठीक किया जा रहा है',
  'step.ready': 'तैयार',
  'processing.waitGemini': 'आमतौर पर करीब 20 सेकंड। यह स्क्रीन खुली रखिए।',
  'processing.waitDemo': 'बस एक पल। यह स्क्रीन खुली रखिए।',
  'processing.label': 'आपका ट्राई-ऑन बन रहा है',

  'result.before': 'आपकी फोटो',
  'result.after': 'यह पहनकर',
  'result.demoNotice': 'यह सिर्फ डेमो है, असली फिटिंग नहीं — कपड़े की फोटो आपकी फोटो पर रखी गई है ताकि स्टाफ जाँच कर सके।',
  'result.save': 'मेरी पसंद में सेव कीजिए',
  'result.share': 'व्हाट्सएप पर घरवालों को भेजिए',
  'result.sharePrivacy': 'भेजने पर यह फोटो टैबलेट से बाहर उसी के पास जाएगी जिसे आप चुनेंगी। आपके भेजे बिना कुछ नहीं जाता।',
  'result.shareGone': 'यह ट्राई-ऑन अब उपलब्ध नहीं है।',
  'result.shareTextOnly': 'इस डिवाइस से सिर्फ मैसेज भेजा जा सका। फोटो भेजने के लिए स्क्रीनशॉट लीजिए।',
  'result.shareNone': 'इस डिवाइस में भेजने की सुविधा नहीं है। फोटो भेजने के लिए स्क्रीनशॉट लीजिए।',
  'result.shareFailed': 'इस डिवाइस पर भेजना नहीं खुल पाया। स्क्रीनशॉट लेकर भेजिए।',
  'result.browse': 'सब कुछ देखिए',
  'result.next': 'अगला ट्राई कीजिए',

  'selection.title': 'मेरी पसंद',
  'selection.empty': 'अभी कुछ सेव नहीं हुआ। कुछ पीस ट्राई कीजिए और जो पसंद आएँ वो यहाँ रखिए।',
  'selection.browse': 'कलेक्शन देखिए',
  'selection.inStock': 'स्टॉक में है',
  'selection.lowStock': 'सिर्फ {n} बचे हैं',
  'selection.outOfStock': 'स्टॉक खत्म',
  'selection.checkout': 'स्टाफ को दिखाइए',
  'selection.checkoutHint': 'स्टाफ सिर्फ यही पीस ट्रायल रूम में लाएगा।',

  'code.title': 'यह किसी भी स्टाफ को दिखाइए',
  'code.label': 'पिकअप कोड',
  'code.photoHere': 'आपकी फोटो अभी टैबलेट में है ताकि आप और पीस ट्राई कर सकें। जब चाहें मिटा दीजिए।',
  'code.deletePhoto': 'मेरी फोटो मिटाइए',
  'code.tryMore': 'और पीस ट्राई कीजिए',
  'code.photoDeleted': 'आपकी फोटो और ट्राई-ऑन इस टैबलेट से मिटा दिए गए हैं। ऊपर वाला कोड अब भी चलेगा।',
  'code.newSelection': 'नई पसंद शुरू कीजिए — फोटो रहने दीजिए',
  'code.finish': 'खत्म — अगला ग्राहक',
  'code.finishHint': 'खत्म करने पर फोटो मिट जाती है और टैबलेट अगले ग्राहक के लिए साफ़ हो जाता है।',

  'error.photoGone': 'आपकी फोटो अब उपलब्ध नहीं है। कृपया दोबारा लीजिए।',
  'error.tryOn': 'ट्राई-ऑन में कुछ गड़बड़ हो गई।',
};

export type T = (key: string, vars?: Record<string, string | number>) => string;

export function makeT(lang: Lang): T {
  const dict = lang === 'hi' ? hi : en;
  return (key, vars) => {
    // Falling back through English means a missing translation shows readable
    // text rather than a key, and a category the shop invented shows its own name.
    let out = dict[key] ?? en[key] ?? key.replace(/^cat\./, '');
    if (vars) for (const [k, v] of Object.entries(vars)) out = out.replaceAll(`{${k}}`, String(v));
    return out;
  };
}

export function useT(): T {
  const { settings } = useStore();
  return useMemo(() => makeT(settings.language), [settings.language]);
}
