import { getFlag, saveImage, setFlag } from './db';
import type { Product } from './types';

/** A seed row carries the filename of its bundled demo illustration. The art is
 *  generated by `npm run seed-images` and lives in `public/seed/`. */
interface SeedProduct extends Product {
  art: string;
}

/** The catalogue the app starts with. Everything here is editable in
 *  Admin → Catalogue; this is only what a fresh install shows, and the art is
 *  drawn, not photographed — it is meant to be replaced piece by piece with
 *  real photos of real stock. */
export const SEED_PRODUCTS: SeedProduct[] = [
  { id: 'p1', name: 'Kanjivaram Silk Saree', cat: 'Sarees', price: 4999, color: 'Maroon', sizes: ['Free size'], stock: 5, createdAt: 1, art: 'seed/saree-kanjivaram.png' },
  { id: 'p2', name: 'Handblock Cotton Kurti', cat: 'Kurtis', price: 899, color: 'Indigo', sizes: ['S', 'M', 'L', 'XL'], stock: 14, createdAt: 2, art: 'seed/kurti-handblock.png' },
  { id: 'p3', name: 'Chikankari Anarkali', cat: 'Kurtis', price: 1699, color: 'Ivory', sizes: ['M', 'L', 'XL'], stock: 6, createdAt: 3, art: 'seed/kurti-anarkali.png' },
  { id: 'p4', name: 'Georgette Party Saree', cat: 'Sarees', price: 2499, color: 'Emerald', sizes: ['Free size'], stock: 8, createdAt: 4, art: 'seed/saree-georgette.png' },
  { id: 'p5', name: 'Floral A-Line Dress', cat: 'Dresses', price: 1299, color: 'Rose', sizes: ['S', 'M', 'L'], stock: 10, createdAt: 5, art: 'seed/dress-aline.png' },
  { id: 'p6', name: 'Sequin Lehenga Set', cat: 'Lehengas', price: 6499, color: 'Wine', sizes: ['S', 'M', 'L'], stock: 3, createdAt: 6, art: 'seed/lehenga-sequin.png' },
  { id: 'p7', name: 'Rayon Straight Kurti', cat: 'Kurtis', price: 749, color: 'Mustard', sizes: ['M', 'L', 'XL'], stock: 18, createdAt: 7, art: 'seed/kurti-rayon.png' },
  { id: 'p8', name: 'Silk Saree Blouse', cat: 'Blouses', price: 649, color: 'Gold', sizes: ['34', '36', '38', '40'], stock: 12, createdAt: 8, art: 'seed/blouse-silk.png' },
];

const ART_FLAG = 'seedArtV1';

/** Copies one bundled illustration into the image store. A missing file is not
 *  worth failing a first run over — the piece just shows without a photo. */
async function loadArt(art: string): Promise<string | undefined> {
  try {
    const res = await fetch(new URL(art, document.baseURI));
    if (!res.ok) return undefined;
    return await saveImage(await res.blob(), 'product');
  } catch {
    return undefined;
  }
}

/** Resolves the catalogue at startup: seeds a fresh install with art attached,
 *  and gives one — and only one — pass of art to installs that were seeded
 *  before the illustrations existed. Returns null when nothing needs saving. */
export async function ensureCatalogue(stored: Product[] | undefined): Promise<Product[] | null> {
  if (!stored?.length) {
    const seeded = await Promise.all(
      SEED_PRODUCTS.map(async ({ art, ...product }) => {
        const imageKey = await loadArt(art);
        return imageKey ? { ...product, imageKey } : product;
      }),
    );
    await setFlag(ART_FLAG);
    return seeded;
  }

  if (await getFlag(ART_FLAG)) return null;
  await setFlag(ART_FLAG);

  // Only untouched seed rows get art — a piece the shop renamed or already
  // photographed is left exactly as it is.
  const byId = new Map(SEED_PRODUCTS.map((p) => [p.id, p]));
  let changed = false;
  const merged = await Promise.all(
    stored.map(async (product) => {
      const seed = byId.get(product.id);
      if (!seed || product.imageKey || product.name !== seed.name) return product;
      const imageKey = await loadArt(seed.art);
      if (!imageKey) return product;
      changed = true;
      return { ...product, imageKey };
    }),
  );
  return changed ? merged : null;
}

/** Four-character pickup code, avoiding characters that read alike on a shelf tag. */
export function makeCode() {
  const alphabet = 'ACDEFGHJKLMNPQRTUVWXY3479';
  let out = '';
  const bytes = new Uint32Array(4);
  crypto.getRandomValues(bytes);
  for (let i = 0; i < 4; i++) out += alphabet[bytes[i] % alphabet.length];
  return out;
}
