import { useStore } from '../store';
import { Camera } from '../components/Camera';
import { Media } from '../components/Img';

const TIPS = [
  'Stand about two steps back, facing the camera',
  'Keep your whole body in frame, head to shoes',
  'A plain wall and good light give the best result',
];

export function Photo() {
  const { settings, back, setDraftPhoto } = useStore();

  return (
    <div className="page">
      <button type="button" className="btn btn--ghost" style={{ alignSelf: 'flex-start' }} onClick={back}>
        ← Back
      </button>

      <h1 className="h-lg">Take your photo</h1>

      <Camera onCapture={setDraftPhoto} />

      <ol className="stack" style={{ listStyle: 'none', margin: 0, padding: 0 }}>
        {TIPS.map((tip, i) => (
          <li key={tip} className="hstack" style={{ gap: 12 }}>
            <span
              aria-hidden="true"
              style={{
                width: 30, height: 30, flex: 'none', borderRadius: 999,
                background: 'var(--color-accent-2-200)', color: 'var(--color-accent-2-800)',
                display: 'grid', placeItems: 'center', fontSize: 13, fontWeight: 700,
              }}
            >
              {i + 1}
            </span>
            <span style={{ fontSize: 14, lineHeight: 1.4, color: 'var(--color-neutral-800)' }}>{tip}</span>
          </li>
        ))}
      </ol>

      {settings.privacyNotice && (
        <p className="notice">
          Your photo stays on this tablet and is never posted anywhere. Delete it yourself at any time
          from the pickup screen, and it goes automatically when the tablet is cleared for the next person.
          {settings.provider === 'gemini' && ' The try-on itself is generated by Google Gemini, so the photo is sent there to be processed.'}
        </p>
      )}
    </div>
  );
}

export function PhotoPreview() {
  const { s, discardDraft, confirmPhoto } = useStore();

  return (
    <div className="page">
      <h1 className="h-lg">Looking good?</h1>

      <Media imageKey={s.draftKey} label="Your photo" />

      <div className="hstack" style={{ flexWrap: 'wrap', gap: 8 }}>
        <span className="badge">Full body visible</span>
        <span className="badge">Good light</span>
      </div>

      <div className="hstack" style={{ gap: 10 }}>
        <button type="button" className="btn btn--outline" style={{ flex: 1 }} onClick={discardDraft}>
          Retake
        </button>
        <button type="button" className="btn btn--primary" style={{ flex: 1.4 }} onClick={confirmPhoto}>
          Use this photo
        </button>
      </div>
    </div>
  );
}
